name: "Request: Generate Learning Plan"
description: "Submit a topic to generate a learning plan"
title: "Plan request: "
labels: ["plan-request"]

body:
   type: input
    id: goal
    attributes:
      label: What is your topic?
      description: "What is your topic?"
      placeholder: "e.g., graph neural networks for molecules"
    validations:
      required: true

  - type: dropdown
    id: top_k
    attributes:
      label: How many papers do you want to learn?
      options:
        - "3"
        - "5"
        - "10"
        - "15"
        - "20"
      default: 2
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: What kind of papers do you prefer?
      description: "This will decide whether we use trending, review, application, or theory mode as input."
      options:
        - "trending"
        - "review"
        - "application"
        - "theory"
      default: 0
    validations:
      required: true